FROM python:3.12

WORKDIR /app

COPY pyproject.toml .
COPY app ./app
COPY mcp_server ./mcp_server


RUN pip install .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]


