[project]
name = "archon-backend"
version = "0.1.0"
description = "Backend for Archon - AI Engineering Architect"
requires-python = ">=3.12,<3.13"
dependencies = [
    "pydantic",
    "langgraph",
    "langchain",
    "langchain-groq",
    "fastapi",
    'langchain-cloudflare',
    "uvicorn",
    "python-dotenv",
    "langchain-google-genai",
    'tavily-python',
    "fastmcp",
     'langchain-mcp-adapters',
]
[tool.setuptools.packages.find]
include = ["app*", "mcp_server*"]