[project]
name = "archon-backend"
version = "0.1.0"
description = "Backend for Archon - AI Engineering Architect"
requires-python = ">=3.12,<3.13"
dependencies = [
    "pydantic",
    "langgraph",
    "langchain",
    "langchain-groq",
    "fastapi",
    'langchain-cloudflare',
    "uvicorn",
    "python-dotenv",
    "langchain-google-genai",
    'tavily-python',
    "fastmcp==3.4.7",
     'langchain-mcp-adapters==0.3.2',
     'mcp==1.29.1',
     'langchain-mistralai',
     "deepeval",
     "httpx",
     "pytest",
]
[tool.setuptools.packages.find]
include = ["app*", "mcp_server*"]